//export const ACTION_TYPE = 'ACTION_TYPE'

export const MAKE_TEST_FALSE = 'MAKE_TEST_FALSE'
export const MAKE_TEST_TRUE = 'MAKE_TEST_TRUE'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const SEND_MESSAGE = 'SEND_MESSAGE'

export const SEND_INVOICE = 'SEND_INVOICE'  //DO THIS FOR INVOICE FORM. SHOULD BE EASY POST TO BILLS WITH USER ID AND BILLED USER ID
export const MARK_AS_PAID = 'MARK_AS_PAID'
export const GET_INVOICES = 'GET_INVOICES'

export const EDIT_BIZ = 'EDIT_BIZ'
export const MAKE_BIZ = 'MAKE_BIZ'
export const GET_BIZZYS = 'GET_BIZZYS'
export const GET_MY_BIZ = 'GET_MY_BIZ'
export const DELETE_BIZ = 'DELETE_BIZ'

export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_MESSAGED_USERS = 'GET_MESSAGED_USERS'

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS'
export const GET_CLIENT_BUSINESSES = 'GET_CLIENT_BUSINESSES'




